code_name = 179
main_chain = "Union Coop"  # change to "Carrefour" to mark Carrefour as 1

pois = [
    {
        "poi_id": 12,
        "name": "Carrefour Motor City",
        "latitude": 25.04653703,
        "longitude": 55.24033921,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Carrefour",
    },
    {
        "poi_id": 6,
        "name": "Carrefour Barsha",
        "latitude": 25.1192935,
        "longitude": 55.2018062,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Carrefour",
    },
    {
        "poi_id": 9,
        "name": "Carrefour Barsha South",
        "latitude": 25.06924142,
        "longitude": 55.24190842,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Carrefour",
    },
    {
        "poi_id": 15,
        "name": "Carrefour Silicon Oasis",
        "latitude": 25.11924749,
        "longitude": 55.39573805,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Carrefour",
    },
    {
        "poi_id": 3,
        "name": "Carrefour Mirdif",
        "latitude": 25.21845589,
        "longitude": 55.40763859,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Carrefour",
    },
    {
        "poi_id": 2,
        "name": "Lulu Mirdif",
        "latitude": 25.23544812,
        "longitude": 55.43554221,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Lulu",
    },
    {
        "poi_id": 7,
        "name": "Union Coop  Barsha South",
        "latitude": 25.08595117,
        "longitude": 55.24169497,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 1,
        "chain": "Union Coop",
    },
    {
        "poi_id": 10,
        "name": "Union Coop  Motor City",
        "latitude": 25.0455452,
        "longitude": 55.23333636,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 1,
        "chain": "Union Coop",
    },
    {
        "poi_id": 4,
        "name": "Union Coop  Barsha",
        "latitude": 25.09901452,
        "longitude": 55.20478672,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 1,
        "chain": "Union Coop",
    },
    {
        "poi_id": 13,
        "name": "Union Coop  Silicon Oasis",
        "latitude": 25.11385369,
        "longitude": 55.38842347,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 1,
        "chain": "Union Coop",
    },
    {
        "poi_id": 1,
        "name": "Union Coop  Mirdif",
        "latitude": 25.23700029,
        "longitude": 55.42122056,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 1,
        "chain": "Union Coop",
    },
    {
        "poi_id": 11,
        "name": "Lulu  Motor City",
        "latitude": 25.04442025,
        "longitude": 55.23016068,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Lulu",
    },
    {
        "poi_id": 14,
        "name": "Lulu  Silicon Oasis",
        "latitude": 25.11112955,
        "longitude": 55.37407178,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Lulu",
    },
    {
        "poi_id": 8,
        "name": "Lulu  Barsha South",
        "latitude": 25.06158774,
        "longitude": 55.22899431,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Lulu",
    },
    {
        "poi_id": 5,
        "name": "Lulu  Barsha",
        "latitude": 25.11720924,
        "longitude": 55.20774114,
        "country": "UAE",
        "city": "Dubai",
        "radius": 100,
        "data_filter": 2,
        "chain": "Lulu",
    },
]
